/*
 * Url Manager Service
 *
 * The URL Manager service provides a set of APIs for managing URL rewrites within your application. URL rewriting is a technique used to modify the appearance or structure of URLs while maintaining the functionality and accessibility of the underlying resources.  The URL Manager service offers various operations to create, retrieve, update, and delete URL rewrite configurations. These configurations allow you to define rules that map incoming URLs to different paths or destinations based on specific criteria. By using URL rewriting, you can enhance the user experience, improve SEO (Search Engine Optimization), and manage complex URL structures effectively.  To get started with the URL Manager service, you need to integrate the provided Proto API into your application. The API supports various programming languages and frameworks, making it easy to incorporate URL rewriting functionality into your existing codebase.  Once integrated, you can utilize the different API methods to create, manage, and query URL rewrite configurations based on your application's requirements.  Refer to the API documentation for detailed information on the request and response formats, authentication requirements, and example usage of each API method.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = urlmanager.Client.OpenAPIDateConverter;

namespace urlmanager.Model
{
    /// <summary>
    /// Defines UrlRewriteRedirectType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum UrlRewriteRedirectType
    {
        /// <summary>
        /// Enum UNKNOWN for value: RedirectType_UNKNOWN
        /// </summary>
        [EnumMember(Value = "RedirectType_UNKNOWN")]
        UNKNOWN = 1,

        /// <summary>
        /// Enum OK for value: RedirectType_OK
        /// </summary>
        [EnumMember(Value = "RedirectType_OK")]
        OK = 2,

        /// <summary>
        /// Enum PERMANENT for value: RedirectType_PERMANENT
        /// </summary>
        [EnumMember(Value = "RedirectType_PERMANENT")]
        PERMANENT = 3,

        /// <summary>
        /// Enum TEMPORARY for value: RedirectType_TEMPORARY
        /// </summary>
        [EnumMember(Value = "RedirectType_TEMPORARY")]
        TEMPORARY = 4
    }

}
